# Supabase local development configuration

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[storage]
enabled = false

[inbucket]
enabled = true
smtp_port = 54324
pop3_port = 54325
port = 54326

[auth]
enabled = true
site_url = "http://localhost:19006"
additional_redirect_urls = ["dorm://auth", "http://localhost:19006"]
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
